controllers/AuthManagementController.php
<?php

namespace app\controllers;

use Yii;
use app\models\auth\AuthItem;
use app\models\auth\AuthItemChild;
use app\models\auth\AuthAssignment;
use yii\data\ActiveDataProvider; 
use app\models\User;
use yii\web\NotFoundHttpException;
use app\components\AdminController;
use yii\filters\AccessControl;

/**
 * 
 */
class AuthManagementController extends AdminController 
{    
    public function behaviors()
    {
        return [  
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create-role', 'update', 'assign', 'manage', 'update-action'],
                'rules' => [                    
                    [
                        'allow' => true,
                        'actions' => ['index', 'create-role', 'update', 'assign', 'manage', 'update-action'],
                        'roles' => ['@'],
                    ],
                ],
            ]            
        ];
    }
    
    public function actionIndex($storeId = null, $name = '') {
        // Cập nhật nhanh mô tả
        if (Yii::$app->request->isAjax && $name != '') {
            $model = AuthItem::findOne([
                'name' => trim($name)
            ]);
            if ($model && $model->load(Yii::$app->request->post()) && !$model->save(true, ['description', 'updated_at'])) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return $model->getErrors();
            }
            return;
        }

        $query = AuthItem::find()
                ->orderBy([
            'type' => SORT_ASC,
            'name' => SORT_ASC
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Màn hình tạo quyền / nhóm quyền
     * @param $storeId
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionCreateRole() {
        $model = new AuthItem;

        $modelAuthItemChild = new AuthItemChild;
        $modelAuthItemChild->scenario = 'createRole';

        if ($model->load(Yii::$app->request->post()) && $modelAuthItemChild->load(Yii::$app->request->post())) {            
            $model->name = trim($model->name);
            // Kiểm tra thông tin Role đã tồn tại
            $authItem = AuthItem::findOne($model->name);
            $model->type = AuthItem::TYPE_USER_PERMISSION;            
            if (!$authItem) {                
                if ($model->save(true, ['name', 'type', 'description', 'created_at', 'updated_at'])) {                    
                    if ($modelAuthItemChild->child) {                       
                        foreach ($modelAuthItemChild->child as $item) {
                            try {
                                $modelAuthItemChild = new AuthItemChild;
                                $modelAuthItemChild->parent = $model->name;
                                $modelAuthItemChild->child = $item;
                                $modelAuthItemChild->save();
                            } catch (Exception $ex) {
                                echo $ex->getMessage();
                            }
                        }
                    }
                    // Xóa cache
                    Yii::$app->authManager->removeCache();
                    Yii::$app->session->setFlash('success', 'Tạo mới thành công.');
                    return $this->redirect(['update', 'name' => $model->name]);
                } else {
                    Yii::$app->session->setFlash('error', 'Đã có lỗi xảy ra, vui lòng thử lại.');
                    return $this->render('create-role', [
                        'model' => $model,
                        'modelAuthItemChild' => $modelAuthItemChild,
                    ]);
                }
            } else {                
                return $this->redirect(['update', 'name' => $authItem->name]);
            }
        }
        return $this->render('create-role', [
            'model' => $model,
            'modelAuthItemChild' => $modelAuthItemChild,
        ]);
    }
    
    
    /**
     * Cập nhật nội dung phân quyền
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($name) {
        $name = trim($name);
        // Thông tin authItem
        $authItem = AuthItem::findOne($name);

        if (!$authItem) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        // Thông tin authItemChild đã được check
        $authItemChild = AuthItemChild::findAll(['parent' => $authItem->name]);

        $authItemChildChecked = [];
        if ($authItemChild) {
            foreach ($authItemChild as $item) {
                $authItemChildChecked[] = $item->child;
            }
        }

        $authItemOldName = $authItem->name;

        $model = new AuthItemChild;

        $model->child = $authItemChildChecked;

        if ($authItem->load(Yii::$app->request->post()) && $model->load(Yii::$app->request->post())) {
            if ($authItem->save(true, ['name', 'description', 'updated_at'])) {
                // Xóa AuthItemChild cũ
                AuthItemChild::deleteAll([
                    'parent' => $authItemOldName,
                    'parent' => $authItem->name
                ]);

                if ($model->child) {
                    foreach ($model->child as $item) {
                        try {
                            $modelAuthItemChild = new AuthItemChild;
                            $modelAuthItemChild->parent = $authItem->name;
                            $modelAuthItemChild->child = $item;
                            $modelAuthItemChild->save();
                        } catch (Exception $ex) {
                            echo $ex->getMessage();
                        }
                    }
                }   
                // Xóa cache
                Yii::$app->authManager->removeCache();
                Yii::$app->session->setFlash('success', 'Cập nhật thành công.');
            } else {
                Yii::$app->session->setFlash('error', 'Đã có lỗi xảy ra, vui lòng thử lại.');
            }
            return $this->redirect(['manage']);
        }
        return $this->render('update', [
                    'model' => $model,
                    'authItem' => $authItem,
        ]);
    }

    /**
     * Gán quyền cho userId
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionAssign($id) {
        $user = User::findOne($id);

        if (!$user) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $model = new AuthAssignment();
        $authAssigned = [];
        $getAssignments = AuthAssignment::find()
                ->where(['user_id' => $id])
                ->all();
        if ($getAssignments) {
            foreach ($getAssignments as $assignmentItem) {
                $authAssigned[] = $assignmentItem->item_name;
            }
        }

        $model->item_name = $authAssigned;

        if ($model->load(\Yii::$app->request->post())) {
            // Xóa đi quyền đã có
            AuthAssignment::deleteAll('user_id = ' . $user->id);

            $dataSave = [];
            $itemsName = $model->item_name;
            if ($itemsName) {
                foreach ($itemsName as $item) {
                    $dataSave[] = [
                        $item, // item_name
                        $id, // user_id,
                        time(), // created_at
                    ];
                }
            }
            if (!empty($dataSave)) {
                $connection = \Yii::$app->db;
                $transaction = $connection->beginTransaction();
                try {
                    $connection->createCommand()->batchInsert(
                        AuthAssignment::tableName(), ['item_name', 'user_id', 'created_at'], $dataSave
                    )->execute();
                    $transaction->commit();
                } catch (Exception $ex) {
                    $transaction->rollBack();
                }
            }
            
            Yii::$app->session->setFlash('success', 'Cập nhật thành công.');
            return $this->redirect(['assign', 'id' => $id]);
        }

        return $this->render('assign', [
            'model' => $model,
            'id' => $id,
        ]);
    }
    
    public function actionManage() {
        $auth = Yii::$app->getAuthManager();
        $query = AuthItem::find()
                ->where(' type=:type AND name!=:name', [':type' => AuthItem::TYPE_USER_PERMISSION, ':name' => $auth->fullAccessName])
                ->orderBy(['name' => SORT_ASC]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('manager', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdateAction() {
        Yii::$app->session->setFlash('success', 'Cập nhật thành công');
        AuthItem::getAllAppActions();      
        return $this->redirect(['manage']);
    }
}

views/auth-management/assign.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\auth\AuthItem;
use app\models\auth\AuthItemChild;

$this->title = 'Gán quyền cho user #'.$id;
$this->params['breadcrumbs'][] = ['label' => 'Nhân viên', 'url' => ['/user']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div id="authitemchild-child">
    <div class="box">
        <div class="box-body">
            <?php $form = ActiveForm::begin(); ?>
            <ul class="list-unstyled">
                <?= $form->field($model, 'item_name')->checkboxList(AuthItem ::getListAuthItemsWithDescription(true), [
                    'item' => function($index, $label, $name, $checked, $value){
                        $checked = $checked == 1 ? ' checked="checked"' : '';
                        return '<li><div class="checkbox" style="margin:0;"><label>'
                        . '<input type="checkbox" name="'.$name.'" value="'.$value.'"'.$checked.'> '.$label.'</label> '
                        . '<i class="glyphicon glyphicon-question-sign help-show-detail" data-toggle="modal" data-target="#help-detail-'.$value.'" style="cursor:pointer;">'
                            . '<div class="popover right span12">
                                <div class="arrow"></div>
                                <h3 class="popover-title">Hướng dẫn</h3>
                                <div class="popover-content">Click xem chi tiết quyền quản trị</div>
                            </div>'
                        . '</i>'
                        . '</div>'
                        . '<div class="modal fade" id="help-detail-'.$value.'" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Chi tiết quyền '.$label.'</h4>
                                    </div>
                                    <div class="modal-body clearfix">'. AuthItemChild::getAuthChild($value).'</div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                           </div>'
                        . '</li>';
                    },
                ])->label(false); ?>
            </ul>
            <div class="form-group no-margin">
                <?= Html::submitButton($this->title, ['class' => 'btn btn-primary']) ?>
            </div>
            <?php $form = ActiveForm::end(); ?>
        </div>
    </div>
</div>
<?php $this->registerJsFile('/js/auth-item.js', ['depends' => [\yii\web\JqueryAsset::className()]]); ?>
<style>
    .help-show-detail .popover{
        width: 250px;
        left: 20px;
        top: -30px;
    }
    .help-show-detail:hover .popover{
        display: block;
    }
    #authassignment-item_name li{
        padding: 10px;
    }
</style>

views/auth-management/create-role.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\auth\AuthItem;

$this->title = 'Tạo quyền / nhóm quyền quản trị';
$this->params['breadcrumbs'][] = ['label' => 'Quản lý phân quyền', 'url' => '/auth-management/manage'];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-management-create-role">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($model, 'name')->textInput(['maxlength' => 64]); ?>
                    <?= $form->field($model, 'description')->textInput(['maxlength' => 64]); ?>
                </div>
                <div class="col-md-8">
                    <ul class="list-unstyled">
                        <?= $form->field($modelAuthItemChild, 'child')->checkboxList(AuthItem::getListAuthItemsWithDescription(), [
                            'item' => function($index, $label, $name, $checked, $value){
                                return '<li><div class="checkbox" style="margin:0;"><label>'
                                . '<input type="checkbox" name="'.$name.'" value="'.$value.'"> '.$label.'</span></label>'
                                . '</div></li>';
                            },
                        ])->label(false); ?>
                    </ul>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton($this->title, ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
    </div>
    <?php $form = ActiveForm::end(); ?>
</div>
<?php $this->registerJsFile('/js/auth-item.js', ['depends' => [\yii\web\JqueryAsset::className()]]); ?>

views/auth-management/index.php
<?php
use yii\grid\GridView;

$this->title = 'Quản lý phân quyền';

//$this->params['breadcrumbs'][] = ['label' => 'Website', 'url' => ['/site/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-management-index">
    <?php if(Yii::$app->session->hasFlash('success')):?>
    <div class="alert alert-success" role="alert">
        <?= Yii::$app->session->getFlash('success'); ?>
    </div>
    <?php endif;?>
    <div class="box">
        <div class="box-body">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    [
                        'header' => 'Name',
                        'content' => function($data){
                            return $data->name;
                        },
                        'contentOptions' => [
                            'style' => 'width: 45%'
                        ]
                    ],
                    'attribute' => 'description',
                ],
                'pager' => [
                    'firstPageLabel' => 'Trang đầu',
                    'lastPageLabel' => 'Trang cuối',
                    'options' => [
                        'class' => 'pagination',
                        'style' => 'margin-bottom: 0;'
                    ]
                ]
            ]); ?>
        </div>
    </div>
</div>
<?php
$js = <<< EOD
    $(function(){
        $('.update-action').click(function(){
            var _this = $(this);
            _this.html('Đang cập nhật...').addClass('disabled');
            $.post(_this.attr('href'), function(result){
                location.reload();
            });
            return false;
        });
    });
EOD;
$this->registerJs($js);
?>

views/auth-management/manager.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
$this->title = 'Quản lý phân quyền';

//$this->params['breadcrumbs'][] = ['label' => 'Danh sách các quyền', 'url' => ['/auth-management/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body" style="margin-bottom: 5px;">
        <?= Html::a('Tạo nhóm quyền',['create-role'],['title'=>'Tạo nhóm quyền mới','class'=>'btn btn-success']) ?>
        <?= Html::a('Cập nhật quyền',['update-action'],['title'=>'Cập nhật quyền','class'=>'btn btn-primary']) ?>
    </div>
</div>
<div class="auth-management-index">
    <div class="box">
        <div class="box-body">
            <?=
            GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'name',
                    'description',
                    ['label'=>'Sửa quyền',
                        'content' => function($data){
                            return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'name' => $data->name]);
                        },
                        'contentOptions' => ['class' => 'text-center','width'=>'1%']
                    ],
                ]
            ]);
            ?>
        </div>
    </div>
</div>

views/auth-management/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\auth\AuthItem;

$this->title = 'Sửa thông tin quyền';
$this->params['breadcrumbs'][] = ['label' => 'Quản lý phân quyền', 'url' => '/auth-management'];
$this->params['breadcrumbs'][] = $this->title;
?>
<!--<h1><?/*= $this->title; */?></h1>-->
<div class="form-group">
<?php $form = ActiveForm::begin(); ?>

    <div class="box">
        <div class="box-body">
            <div class="row">
                <div class="col-md-4">
                    <?= $form->field($authItem, 'name')->textInput(['maxlength' => 64]); ?>
                    <?= $form->field($authItem, 'description')->textInput(['maxlength' => 64]); ?>
                </div>
                <div class="col-md-8" id="authitemchild-child">
                    <ul class="list-unstyled">
                        <?= $form->field($model, 'child')->checkboxList(AuthItem::getListAuthItemsWithDescription(), [
                            'item' => function($index, $label, $name, $checked, $value){
                                $check = $checked == 1 ? ' checked="checked"' : '';
                                return '<li><div class="checkbox" style="margin:0;"><label>'
                                . '<input type="checkbox" name="'.$name.'" value="'.$value.'"'.$check.'> '.$label.'</span></label>'
                                . '</div></li>';
                            },
                        ])->label(false); ?>
                    </ul>
                </div>
            </div>

            <?= Html::submitButton('Cập nhật', ['class' => 'btn btn-primary','name'=>'btnUpdate']) ?>
        </div>
    </div>

<?php ActiveForm::end();?>
</div>
<?php $this->registerJsFile('/js/auth-item.js', ['depends' => [\yii\web\JqueryAsset::className()]]); ?>