controllers/AuthManagementController.php
<?php

namespace app\controllers;

use Yii;
use app\models\auth\AuthItem;
use app\models\auth\AuthItemChild;
use app\models\auth\AuthAssignment;
use yii\data\ActiveDataProvider; 
use app\models\User;
use yii\web\NotFoundHttpException;
use app\components\AdminController;
use yii\filters\AccessControl;

/**
 * 
 */
class AuthManagementController extends AdminController 
{    
    public function behaviors()
    {
        return [  
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create-role', 'update', 'assign', 'manage', 'update-action'],
                'rules' => [                    
                    [
                        'allow' => true,
                        'actions' => ['index', 'create-role', 'update', 'assign', 'manage', 'update-action'],
                        'roles' => ['@'],
                    ],
                ],
            ]            
        ];
    }
    
    public function actionIndex($storeId = null, $name = '') {
        // Cập nhật nhanh mô tả
        if (Yii::$app->request->isAjax && $name != '') {
            $model = AuthItem::findOne([
                'name' => trim($name)
            ]);
            if ($model && $model->load(Yii::$app->request->post()) && !$model->save(true, ['description', 'updated_at'])) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return $model->getErrors();
            }
            return;
        }

        $query = AuthItem::find()
                ->orderBy([
            'type' => SORT_ASC,
            'name' => SORT_ASC
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Màn hình tạo quyền / nhóm quyền
     * @param $storeId
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionCreateRole() {
        $model = new AuthItem;

        $modelAuthItemChild = new AuthItemChild;
        $modelAuthItemChild->scenario = 'createRole';

        if ($model->load(Yii::$app->request->post()) && $modelAuthItemChild->load(Yii::$app->request->post())) {            
            $model->name = trim($model->name);
            // Kiểm tra thông tin Role đã tồn tại
            $authItem = AuthItem::findOne($model->name);
            $model->type = AuthItem::TYPE_USER_PERMISSION;            
            if (!$authItem) {                
                if ($model->save(true, ['name', 'type', 'description', 'created_at', 'updated_at'])) {                    
                    if ($modelAuthItemChild->child) {                       
                        foreach ($modelAuthItemChild->child as $item) {
                            try {
                                $modelAuthItemChild = new AuthItemChild;
                                $modelAuthItemChild->parent = $model->name;
                                $modelAuthItemChild->child = $item;
                                $modelAuthItemChild->save();
                            } catch (Exception $ex) {
                                echo $ex->getMessage();
                            }
                        }
                    }
                    // Xóa cache
                    Yii::$app->authManager->removeCache();
                    Yii::$app->session->setFlash('success', 'Tạo mới thành công.');
                    return $this->redirect(['update', 'name' => $model->name]);
                } else {
                    Yii::$app->session->setFlash('error', 'Đã có lỗi xảy ra, vui lòng thử lại.');
                    return $this->render('create-role', [
                        'model' => $model,
                        'modelAuthItemChild' => $modelAuthItemChild,
                    ]);
                }
            } else {                
                return $this->redirect(['update', 'name' => $authItem->name]);
            }
        }
        return $this->render('create-role', [
            'model' => $model,
            'modelAuthItemChild' => $modelAuthItemChild,
        ]);
    }
    
    
    /**
     * Cập nhật nội dung phân quyền
     * @param string $name
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionUpdate($name) {
        $name = trim($name);
        // Thông tin authItem
        $authItem = AuthItem::findOne($name);

        if (!$authItem) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        // Thông tin authItemChild đã được check
        $authItemChild = AuthItemChild::findAll(['parent' => $authItem->name]);

        $authItemChildChecked = [];
        if ($authItemChild) {
            foreach ($authItemChild as $item) {
                $authItemChildChecked[] = $item->child;
            }
        }

        $authItemOldName = $authItem->name;

        $model = new AuthItemChild;

        $model->child = $authItemChildChecked;

        if ($authItem->load(Yii::$app->request->post()) && $model->load(Yii::$app->request->post())) {
            if ($authItem->save(true, ['name', 'description', 'updated_at'])) {
                // Xóa AuthItemChild cũ
                AuthItemChild::deleteAll([
                    'parent' => $authItemOldName,
                    'parent' => $authItem->name
                ]);

                if ($model->child) {
                    foreach ($model->child as $item) {
                        try {
                            $modelAuthItemChild = new AuthItemChild;
                            $modelAuthItemChild->parent = $authItem->name;
                            $modelAuthItemChild->child = $item;
                            $modelAuthItemChild->save();
                        } catch (Exception $ex) {
                            echo $ex->getMessage();
                        }
                    }
                }   
                // Xóa cache
                Yii::$app->authManager->removeCache();
                Yii::$app->session->setFlash('success', 'Cập nhật thành công.');
            } else {
                Yii::$app->session->setFlash('error', 'Đã có lỗi xảy ra, vui lòng thử lại.');
            }
            return $this->redirect(['manage']);
        }
        return $this->render('update', [
                    'model' => $model,
                    'authItem' => $authItem,
        ]);
    }

    /**
     * Gán quyền cho userId
     * @param $id
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionAssign($id) {
        $user = User::findOne($id);

        if (!$user) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $model = new AuthAssignment();
        $authAssigned = [];
        $getAssignments = AuthAssignment::find()
                ->where(['user_id' => $id])
                ->all();
        if ($getAssignments) {
            foreach ($getAssignments as $assignmentItem) {
                $authAssigned[] = $assignmentItem->item_name;
            }
        }

        $model->item_name = $authAssigned;

        if ($model->load(\Yii::$app->request->post())) {
            // Xóa đi quyền đã có
            AuthAssignment::deleteAll('user_id = ' . $user->id);

            $dataSave = [];
            $itemsName = $model->item_name;
            if ($itemsName) {
                foreach ($itemsName as $item) {
                    $dataSave[] = [
                        $item, // item_name
                        $id, // user_id,
                        time(), // created_at
                    ];
                }
            }
            if (!empty($dataSave)) {
                $connection = \Yii::$app->db;
                $transaction = $connection->beginTransaction();
                try {
                    $connection->createCommand()->batchInsert(
                        AuthAssignment::tableName(), ['item_name', 'user_id', 'created_at'], $dataSave
                    )->execute();
                    $transaction->commit();
                } catch (Exception $ex) {
                    $transaction->rollBack();
                }
            }
            
            Yii::$app->session->setFlash('success', 'Cập nhật thành công.');
            return $this->redirect(['assign', 'id' => $id]);
        }

        return $this->render('assign', [
            'model' => $model,
            'id' => $id,
        ]);
    }
    
    public function actionManage() {
        $auth = Yii::$app->getAuthManager();
        $query = AuthItem::find()
                ->where(' type=:type AND name!=:name', [':type' => AuthItem::TYPE_USER_PERMISSION, ':name' => $auth->fullAccessName])
                ->orderBy(['name' => SORT_ASC]);

        $dataProvider = new ActiveDataProvider([
            'query' => $query
        ]);

        return $this->render('manager', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionUpdateAction() {
        Yii::$app->session->setFlash('success', 'Cập nhật thành công');
        AuthItem::getAllAppActions();      
        return $this->redirect(['manage']);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\User;
use app\models\search\UserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\AdminController;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new User();

        if ($model->load(Yii::$app->request->post())) {
            if(!$model->password_hash || $model->password_hash == '') {
                $model->setPassword(User::DEFAULT_PASSWORD);
            } else {
                $model->setPassword($model->password_hash);
            }
            $model->generateAuthKey();
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }
    
    public function actionChangePassword() {
        $this->checkLogin();
        $resetPasswordModel = new \app\models\form\ResetPasswordForm();
        if ($resetPasswordModel->load(Yii::$app->request->post())) {
            $user = $this->findModel(Yii::$app->user->id);
            if ($resetPasswordModel->validate()) {
                $user->setPassword($resetPasswordModel->change_password);
                $user->generateAuthKey();
                if($user->reset_password_require == User::RESET_PWD_REQUIRE) {
                    $user->reset_password_require = User::RESET_PWD_NOT_REQUIRE;
                }
                if ($user->save(true, ['password_hash','auth_key', 'reset_password_require'])) {
                    Yii::$app->user->logout();
                    return $this->redirect(['/site/login']);
                } else {
                    Yii::$app->session->setFlash ('error','Không thay đổi được mật khẩu');
                }
            }
        }
        return $this->render('change_password', [
            'model' => $resetPasswordModel
        ]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
    
    <?php if($model->isNewRecord) echo $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/change_password.php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Cập nhật mật khẩu';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box">
    <div class="box-body">
        <?php $form = ActiveForm::begin();        
        ?>
            <div class="form-group">
            <label class="control-label">Username: </label>
            <label style="line-height:30px;"><?php echo Yii::$app->user->identity->username;  ?> </label>
        </div>
            <?= $form->field($model, 'password')->passwordInput(['placeholder'=>'Mật khẩu hiện tại']) ?>
        <?= $form->field($model, 'change_password')->passwordInput(['placeholder'=>'Gõ lại mật khẩu mới']) ?>
            <?= $form->field($model, 'change_password_repeate')->passwordInput(['placeholder'=>'Gõ lại mật khẩu mới']) ?>
        <div class="form-group">
            <label class="control-label"></label>
        <?= Html::submitButton('Lưu mật khẩu', ['class'=>'btn btn-success'])?>
        </div>
                
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create User', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'username',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            //'email:email',
            //'phone',
            //'status',
            'created_at:date',
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons'  => [
                    'assign-btn' => function($url, $model) {
                        $url = Yii::$app->urlManager->createUrl(['auth-management/assign', 'id' => $model->id]);
                        return '<a title="Phân quyền" aria-label="Phân quyền" href="'.$url.'" style="text-decoration:none"><span class="glyphicon glyphicon-queen" aria-hidden="true"></span></a>';
                    }
                ],
                'template' => '{view} &nbsp; {update} &nbsp; {delete} &nbsp; {assign-btn}',
            ],
        ],
    ]); ?>
</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/user/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Chi tiết #'.$model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="user-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            'email:email',
            'phone',
            //'status',
            //'created_at',
            //'updated_at',
        ],
    ]) ?>

</div>