models/FbPage.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "fb_page".
 *
 * @property int $id
 * @property int $page_type
 * @property string $page_id
 * @property string $page_name
 * @property int $created_by
 * @property int $created_at
 * @property int $updated_at
 * @property int $status_code
 * @property string $branch
 * @property string $sub_branch
 * @property string $keyword
 * @property string $page_category
 * @property string $page_about
 * @property string $page_description
 * @property string $page_city
 * @property string $page_country
 * @property int $page_like
 * @property string $group_page
 * @property string $status
 */
class FbPage extends \yii\db\ActiveRecord
{
    const TYPE_GROUP = 0;
    const TYPE_PAGE = 1;
    
    const STATUS_ACTIVE = 10;
    const STATUS_DELETE = 0;
    const STATUS_INACTIVE = 5;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'fb_page';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['page_type', 'created_by', 'created_at', 'updated_at', 'status_code', 'page_like', 'status'], 'integer'],
            [['page_about', 'page_description', 'page_country', 'group_page'], 'string'],
            [['page_id', 'page_name', 'branch', 'sub_branch', 'page_category', 'page_city'], 'string', 'max' => 255],
            ['page_id', 'unique'],
            [['keyword'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'page_type' => 'Loại trang',
            'page_id' => 'ID Trang',
            'page_name' => 'Tên trang',
            'created_by' => 'Lưu bởi',
            'created_at' => 'Lưu lúc',
            'updated_at' => 'Cập nhật lúc',
            'status_code' => 'Status Code',
            'branch' => 'Branch',
            'sub_branch' => 'Sub Branch',
            'keyword' => 'Từ khóa',
            'page_category' => 'Lĩnh vực',
            'page_about' => 'Page About',
            'page_description' => 'Page Description',
            'page_city' => 'Page City',
            'page_country' => 'Page Country',
            'page_like' => 'Page Like',
            'group_page' => 'Nhóm',
            'status' => 'Trạng thái'
        ];
    }
    
    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className()
            ],
        ];
    }
    
    public static function getTypeLabels() {
        return [
            self::TYPE_GROUP => 'Nhóm',
            self::TYPE_PAGE => 'Trang',
        ];
    }
    
    public static function getStatusLabels() {
        return [
            self::STATUS_ACTIVE => 'Đang quét dữ liệu',
            self::STATUS_INACTIVE => 'Đã dừng quét',
            self::STATUS_DELETE =>'Đã xóa'
        ];
    }


    public function getUser() {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    
    public static function getListPageByKeyword($keywords) {
        $query = FbPage::find()->select('page_id');
        
        foreach ($keywords as $k => $kw) {
            //$query->orFilterWhere(['like','keyword', $kw]);
            $param = ':kw_'.$k;
            $query->orWhere(new \yii\db\Expression("FIND_IN_SET({$param},`keyword`)"));
            $query->addParams([$param => $kw]);
        }
        $query->andFilterWhere(['IN', 'status', [FbPage::STATUS_ACTIVE, FbPage::STATUS_INACTIVE]]);
        $res = $query->all();
        $list = [];
        foreach ($res as $rs){
            $list[] = $rs->page_id;
        }
        return $list;
    }
    
    public static function deleteByKeyword($keyword) {
        $query = FbPage::find();
        $query->orWhere(new \yii\db\Expression("FIND_IN_SET(:kw,`keyword`)"));
        $query->addParams([':kw' => $keyword]);
        $query->andFilterWhere(['status' => FbPage::STATUS_INACTIVE]);
        $rows = $query->all();
        foreach($rows as $row) {
            $curentKw = explode(',', $row->keyword);
            if (($key = array_search($keyword, $curentKw)) !== false) {
                unset($curentKw[$key]);
            }
            if(sizeof($curentKw) == 0) {
                $row->status = FbPage::STATUS_DELETE;
                if($row->save(true, ['status'])) {
                    es\ElasticData::deleteByPageId($row->page_id);
                }
            } else {
                $row->keyword = implode(',', $curentKw);
                $row->save(true, ['keyword']);
            }
        }
        return true;
    }
    
    public static function updateStatusByKeyword($keyword, $status) {
        $query = FbPage::find();
        $query->orWhere(new \yii\db\Expression("FIND_IN_SET(:kw,`keyword`)"));
        $query->addParams([':kw' => $keyword]);
        //$query->andFilterWhere(['status' => FbPage::STATUS_ACTIVE]);
        $rows = $query->all();
        foreach($rows as $row) {
            $row->status = $status;
            $row->save(true, ['status']);
        }
        return true;
    }
    
    public static function updateKeywordByKeyword($searcher, $replacer) {
        $query = FbPage::find();
        $query->where(new \yii\db\Expression("FIND_IN_SET(:kw,`keyword`)"));
        $query->addParams([':kw' => $searcher]);
        
        $rows = $query->all();
        foreach($rows as $row) {
            $row->keyword = str_replace($searcher, $replacer, $row->keyword);
            $row->save(true, ['keyword']);
        }
        return true;
    }

    public static function getPageNameByPageId($pageId) {
        $m = FbPage::find()->select('page_name')->where(['page_id' => $pageId])->one();
        if($m) {
            return $m->page_name;
        }
        return '';
    }
}

controllers/FbPageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\FbPage;
use app\models\search\FbPageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\AdminController;
use app\models\es\FacebookData;

/**
 * FbPageController implements the CRUD actions for FbPage model.
 */
class FbPageController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all FbPage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new FbPageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        /*return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);*/
        return $this->render('index2', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single FbPage model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new FbPage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new FbPage();

        if ($model->load(Yii::$app->request->post())) {
            if(is_array($model->keyword) && !empty($model->keyword)) {
                $model->keyword = implode(',', $model->keyword);
            }
            $model->created_by = Yii::$app->user->id;
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
            
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing FbPage model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if(is_array($model->keyword) && !empty($model->keyword)) {
                $model->keyword = implode(',', $model->keyword);
            }
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing FbPage model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();
        $model = $this->findModel($id);
        if($model->status != FbPage::STATUS_INACTIVE) {
            Yii::$app->session->setFlash('error', 'Bạn phải dừng quét trước khi xóa dữ liệu');
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
        $model->status = FbPage::STATUS_DELETE;
        if($model->save(true, ['status'])) {
            \app\models\es\ElasticData::deleteByPageId($model->page_id);
        }

        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }
    
    public function actionPause($id) {
        $model = $this->findModel($id);
        $model->status = FbPage::STATUS_INACTIVE;
        if($model->save(true, ['status'])) {
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
    }
    
    public function actionRecrawl($id) {
        $model = $this->findModel($id);
        $model->status = FbPage::STATUS_ACTIVE;
        if($model->save(true, ['status'])) {
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
    }

    /**
     * Finds the FbPage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return FbPage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = FbPage::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/KeywordController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Keyword;
use app\models\search\KeywordSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\components\AdminController;
use yii\db\Query;

/**
 * KeywordController implements the CRUD actions for Keyword model.
 */
class KeywordController extends AdminController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Keyword models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KeywordSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Keyword model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Keyword model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Keyword();
        
        if ($model->load(Yii::$app->request->post())) {
            $model->created_by = Yii::$app->user->id;
            $model->keyword = strtolower($model->keyword);
            if($model->save()) {
                return $this->redirect(['index']);
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Keyword model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        /*
        $curentKw = $model->keyword;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            \app\models\FbPage::updateKeywordByKeyword($curentKw, $model->keyword);
            return $this->redirect(['view', 'id' => $model->id]);
        }*/
        Yii::$app->session->setFlash('error', 'Chức năng này bị khóa vĩnh viễn');
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Keyword model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //$this->findModel($id)->delete();
        $model = $this->findModel($id);
        if($model->status != Keyword::STATUS_INACTIVE) {
            Yii::$app->session->setFlash('error', 'Bạn phải dừng quét trước khi xóa dữ liệu');
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
        $model->status = Keyword::STATUS_DELETE;
        if($model->save(true, ['status'])) {
            \app\models\FbPage::deleteByKeyword($model->keyword);
        }
        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }
    
    public function actionPause($id) {
        $model = $this->findModel($id);
        $model->status = Keyword::STATUS_INACTIVE;
        if($model->save(true, ['status'])) {
            \app\models\FbPage::updateStatusByKeyword($model->keyword, \app\models\FbPage::STATUS_INACTIVE);
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
    }
    
    public function actionRecrawl($id) {
        $model = $this->findModel($id);
        $model->status = Keyword::STATUS_ACTIVE;
        if($model->save(true, ['status'])) {
            \app\models\FbPage::updateStatusByKeyword($model->keyword, \app\models\FbPage::STATUS_ACTIVE);
            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
    }
    
    
    public function actionAjaxKeywordList($q = null) {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $query = new Query;
            $query->select('keyword as id, keyword AS text')
                ->from('keyword')
                ->where(['like', 'keyword', $q])
                ->andWhere(['IN', 'status', [Keyword::STATUS_ACTIVE, Keyword::STATUS_INACTIVE]])
                ->limit(20);
            $command = $query->createCommand();
            $data = $command->queryAll();
            $out['results'] = array_values($data);
        }
        return $out;
    }

    /**
     * Finds the Keyword model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Keyword the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Keyword::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/fb-page/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\FbPage */
/* @var $form yii\widgets\ActiveForm */

$url = \yii\helpers\Url::to(['/keyword/ajax-keyword-list']);
use kartik\select2\Select2;
use yii\web\JsExpression;

?>


<div class="row">
    <?php $form = ActiveForm::begin(); ?>
    <div class="fb-page-form col-md-6">
        <?= $form->field($model, 'page_type')->dropDownList(['' => '----Chọn loại----'] + app\models\FbPage::getTypeLabels()) ?>

        <?= $form->field($model, 'page_id')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'page_name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'branch')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'sub_branch')->textInput(['maxlength' => true]) ?> 

        <?php //echo $form->field($model, 'keyword')->textInput(['maxlength' => true]) ?>
        <?php 
        if($model->keyword && $model->keyword != '')$model->keyword = explode(',', $model->keyword);
        echo $form->field($model, 'keyword', ['errorOptions' => ['tag' => null]])->widget(Select2::classname(), [
            'options' => ['placeholder' => 'Nhập từ khóa...', 'multiple' => true],
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 2,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                ],
                'ajax' => [
                    'url' => $url,
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                'templateResult' => new JsExpression('function(city) { return city.text; }'),
                'templateSelection' => new JsExpression('function (city) { return city.text; }'),
                'width' => '100%'
            ],
        ]);
        ?>
        <div class="form-group">
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>
    </div>
    <div class="fb-page-form col-md-6">
        <?= $form->field($model, 'group_page')->textInput(['maxlength' => true]) ?> 

        <?= $form->field($model, 'page_category')->textInput(['maxlength' => true]) ?> 

        <?= $form->field($model, 'page_about')->textInput(['maxlength' => true]) ?> 

        <?= $form->field($model, 'page_description')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'page_city')->textInput(['maxlength' => true]) ?> 

        <?= $form->field($model, 'page_country')->textInput(['maxlength' => true]) ?> 
 
    </div>
    <?php ActiveForm::end(); ?>
</div>
    

views/fb-page/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\FbPageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="fb-page-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'page_type') ?>

    <?= $form->field($model, 'page_id') ?>

    <?= $form->field($model, 'page_name') ?>

    <?= $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'status_code') ?>

    <?php // echo $form->field($model, 'branch') ?>

    <?php // echo $form->field($model, 'sub_branch') ?>

    <?php // echo $form->field($model, 'keyword') ?>

    <?php // echo $form->field($model, 'page_category') ?>

    <?php // echo $form->field($model, 'page_about') ?>

    <?php // echo $form->field($model, 'page_description') ?>

    <?php // echo $form->field($model, 'page_city') ?>

    <?php // echo $form->field($model, 'page_country') ?>

    <?php // echo $form->field($model, 'page_like') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/fb-page/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FbPage */

$this->title = 'Create Fb Page';
$this->params['breadcrumbs'][] = ['label' => 'Fb Pages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fb-page-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/fb-page/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\FbPageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Facebook Pages';
$this->params['breadcrumbs'][] = $this->title;

$showFull= \Yii::$app->request->get('show_full','');
$options = [];
$visible = true;
if($showFull == '') {
    $options = ['class' => 'hidden'];
    $visible = false;
}
?>
<div class="fb-page-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Page', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Create Keyword', ['keyword/create'], ['class' => 'btn btn-info']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            //'page_type',
            'page_id',
            'page_name',
            //'created_by',
            ['attribute' => 'Lưu bởi','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->user->username;
            }],
            ['attribute' => 'Tạo lúc','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return date('Y-m-d h:i:s',$model->created_at);
            }],
            ['attribute' => 'Cập nhật lúc','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return date('Y-m-d h:i:s',$model->updated_at);
            }],
            //'created_at:date',
            //'updated_at',
            //'status_code',
            //'branch',
            ['attribute' => 'Branch','headerOptions' => $options, 'visible' => $visible,'format' => 'raw', 'value' => function($model) {
                return $model->branch;
            }],
            //'sub_branch',
            ['attribute' => 'Sub Branch','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->sub_branch;
            }],
            'keyword',
            ['attribute' => 'status', 'format' => 'raw', 
                'filter' => app\models\FbPage::getStatusLabels(),
                'filterInputOptions' => ['class' => 'form-control', 'id' => null, 'prompt' => 'Tất cả trạng thái'],
                'value' => function($model) {
                $label = 'label-success';
                if($model->status == \app\models\FbPage::STATUS_INACTIVE) {
                    $label = 'label-warning';
                }
                $status = isset(\app\models\FbPage::getStatusLabels()[$model->status])
                        ?'<p><span class="label '.$label.'">'.\app\models\FbPage::getStatusLabels()[$model->status].'</span></p>':'';
                return (isset(app\models\FbPage::getTypeLabels()[$model->page_type])?app\models\FbPage::getTypeLabels()[$model->page_type]:'').$status;
            }],
            //'group',
            ['attribute' => 'Group','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->group_page;
            }],
            
            //'page_category',
            ['attribute' => 'Page Category','headerOptions' => $options, 'visible' => $visible,'format' => 'raw', 'value' => function($model) {
                return $model->page_category;
            }],
            //'page_about:ntext',
            ['attribute' => 'Page About','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->page_about;
            }],
            //'page_description:ntext',
            ['attribute' => 'Page Description','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->page_description;
            }],
            //'page_city',
            ['attribute' => 'Page City','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->page_city;
            }],
            //'page_country:ntext',
            ['attribute' => 'Page Country','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->page_country;
            }],
            //'page_like',
            ['attribute' => 'Page Like','headerOptions' => $options,'visible' => $visible, 'format' => 'raw', 'value' => function($model) {
                return $model->page_like;
            }],
                    
            //['class' => 'yii\grid\ActionColumn'],
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons'  => [
                    'link-btn' => function($url, $model) {
                        $url = 'https://facebook.com/'.$model->page_id;
                        return '<a title="Xem trang" aria-label="Xem trang" href="'.$url.'" target="_blank" style="text-decoration:none"><span class="glyphicon glyphicon-link" aria-hidden="true"></span></a>';
                    },
                    'pause-btn' => function($url, $model) {
                        $url = '/fb-page/pause?id='.$model->id;
                        $res =  '<a title="Tạm dừng" aria-label="Tạm dừng" href="'.$url.'" style="text-decoration:none">'
                                .   '<span class="glyphicon glyphicon-pause" aria-hidden="true"></span>'
                                . '</a>';
                        if($model->status == \app\models\FbPage::STATUS_INACTIVE) {
                            $url = '/fb-page/recrawl?id='.$model->id;
                            $res =  '<a title="Chạy lại" aria-label="Chạy lại" href="'.$url.'" style="text-decoration:none">'
                                .   '<span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span>'
                                . '</a>';
                        }
                        
                        return $res;
                    }
                ],
                'template' => '{view} &nbsp; {update} &nbsp; {delete} &nbsp; {pause-btn} &nbsp; {link-btn}',
            ],
        ],
    ]); ?>
</div>

views/fb-page/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\FbPage */

$this->title = 'Update Fb Page: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Fb Pages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="fb-page-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/fb-page/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\FbPage */

$this->title = 'Chi tiết trang #'.$model->id;
$this->params['breadcrumbs'][] = ['label' => 'Fb Pages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="fb-page-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            //'page_type',
            [
                'label' => 'Loại trang',
                'format' => 'raw',
                'value' => isset(app\models\FbPage::getTypeLabels()[$model->page_type])?'<b>'. app\models\FbPage::getTypeLabels()[$model->page_type].'</b>':''
            ],
            //'page_id',
            [
                'label' => 'ID trang',
                'format' => 'raw',
                'value' => '<a target="_blank" href="https://facebook.com/'.$model->page_id.'">'. $model->page_id. '</a>'
            ],
            [
                'label' => 'Tên trang',
                'format' => 'raw',
                'value' => '<a target="_blank" href="https://facebook.com/'.$model->page_id.'">'. $model->page_name. '</a>'
            ],
            //'page_name',
            [
                'label' => 'Lưu bởi',
                'format' => 'raw',
                'value' => '<b>'. $model->user->username.'</b>'
            ],
            //'created_by',
            'created_at:date',
            'updated_at:date',
            //'status_code',
            //'branch',
            //'sub_branch',
            'keyword',
            //'page_category',
            //'page_about:ntext',
            //'page_description:ntext',
            //'page_city',
            //'page_country:ntext',
            //'page_like',
        ],
    ]) ?>

</div>